name: Build and Release CuteCapture
on:
  push:
    branches: [master, gh-actions]
  pull_request:
    branches: [master]
jobs:
  linux:
    runs-on: ubuntu-latest
    outputs:
      upload_url: ${{ steps.create_release.outputs.upload_url }}
      id: ${{ steps.create_release.outputs.id }}
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Build
        run: |
          sudo apt-get install -y libusb-1.0.0-dev libsfml-dev
          ./autogen.sh && ./configure && make
          chmod +x Cute3DSCapture
      - name: Get current date
        id: date
        run: echo "::set-output name=date::$(date +'%Y-%m-%d_%H-%M-%S')"
      - name: Create Draft Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ steps.date.outputs.date }}
          release_name: Release ${{ steps.date.outputs.date }}
          draft: true
          prerelease: true
      - name: Upload Binary
        uses: actions/upload-release-asset@v1.0.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./Cute3DSCapture
          asset_name: Cute3DSCapture.linux
          asset_content_type: application/octet-stream
  macos:
    runs-on: macOS-latest
    needs: [linux]
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Build
        run: |
          # versions: libusb@1.0.23 and sfml@2.5.1 at time of writing
          brew install autoconf automake libtool libusb sfml
          ./autogen.sh && ./configure && make
      - name: Link Deps
        run: |
          # copy these dynamic libs and inter-deps over to be bundled, change perms
          cp /usr/local/opt/libusb/lib/libusb-1.0.0.dylib /usr/local/opt/sfml/lib/libsfml-window.2.5.dylib /usr/local/opt/sfml/lib/libsfml-graphics.2.5.dylib /usr/local/opt/sfml/lib/libsfml-system.2.5.dylib .
          cp /usr/local/opt/libpng/lib/libpng16.16.dylib /usr/local/opt/freetype/lib/libfreetype.6.dylib .
          chmod 777 *.dylib
          chmod +x Cute3DSCapture

          # edit binary to have libusb and sfml relatively linked (can check with otool -L Cute3DSCapture to see current dylib paths)
          install_name_tool -change /usr/local/opt/libusb/lib/libusb-1.0.0.dylib @executable_path/libusb-1.0.0.dylib Cute3DSCapture
          install_name_tool -change /usr/local/opt/sfml/lib/libsfml-window.2.5.dylib @executable_path/libsfml-window.2.5.dylib Cute3DSCapture
          install_name_tool -change /usr/local/opt/sfml/lib/libsfml-graphics.2.5.dylib @executable_path/libsfml-graphics.2.5.dylib Cute3DSCapture
          install_name_tool -change /usr/local/opt/sfml/lib/libsfml-system.2.5.dylib @executable_path/libsfml-system.2.5.dylib Cute3DSCapture

          # adjust some of the dylibs to internally reference these relative dylibs as well (can also check with otool -L <dylib>)
          install_name_tool -change @rpath/libsfml-window.2.5.dylib @executable_path/libsfml-window.2.5.dylib ./libsfml-graphics.2.5.dylib
          install_name_tool -change @rpath/libsfml-system.2.5.dylib @executable_path/libsfml-system.2.5.dylib ./libsfml-graphics.2.5.dylib
          install_name_tool -change @rpath/libsfml-system.2.5.dylib @executable_path/libsfml-system.2.5.dylib ./libsfml-window.2.5.dylib

          # some more inter-dependent dylibs
          install_name_tool -change /usr/local/opt/libpng/lib/libpng16.16.dylib @executable_path/libpng16.16.dylib ./libfreetype.6.dylib
          install_name_tool -change /usr/local/opt/freetype/lib/libfreetype.6.dylib @executable_path/libfreetype.6.dylib ./libsfml-graphics.2.5.dylib
      - name: Create App Bundle
        run: |
          mkdir -p Cute3DSCapture.app/Contents/MacOS
          cp Cute3DSCapture *.dylib Cute3DSCapture.app/Contents/MacOS
          cp Info.plist Cute3DSCapture.app/Contents
          zip -r Cute3DSCapture.zip Cute3DSCapture.app
      - name: Upload Zip
        uses: actions/upload-release-asset@v1.0.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ needs.linux.outputs.upload_url }}
          asset_path: ./Cute3DSCapture.zip
          asset_name: Cute3DSCapture.mac.zip
          asset_content_type: application/zip
      - name: Publish Release
        uses: eregon/publish-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          release_id: ${{ needs.linux.outputs.id }}